"""Isolated T2 compose project (`govpilot-t2`): config generation + lifecycle.

The gateway configs are GENERATED from deploy/litellm/config.yaml (no drift from
the production config) with test-only additions:
  - mock-runaway          provider that ignores max_tokens (tests/budget/stack/runaway_provider.py)
  - mock-local-broken     deployment on a dead port, router fallback -> mock-remote
  - mock-local-dead       deployment on a dead port, no router fallback (request-body fallbacks)
  - mock-flaky            one dead + one good deployment (retry tests; cooldowns disabled)
  - proxy_batch_write_at  raised to LAG_SECONDS to widen the DB spend-log lag window
The native config is identical minus litellm_settings.callbacks.

CLI:  python tests/budget/stack/t2stack.py up|down|configs
"""
from __future__ import annotations

import copy
import os
import pathlib
import subprocess
import sys

import yaml

ROOT = pathlib.Path(__file__).resolve().parents[3]
OUT = ROOT / ".local" / "t2"
PROJECT = "govpilot-t2"
GUARDED_PORT = int(os.getenv("T2_GUARDED_PORT", "4100"))
NATIVE_PORT = int(os.getenv("T2_NATIVE_PORT", "4101"))
LAG_SECONDS = 15
COMPOSE_FILES = [ROOT / "deploy" / "docker-compose.yml", ROOT / "tests" / "budget" / "stack" / "docker-compose.t2.yml"]
CONTAINERS = {"postgres": "t2-postgres", "redis": "t2-redis", "gateway": "t2-gateway",
              "gateway-native": "t2-gateway-native", "mock-local": "t2-mock-local",
              "mock-remote": "t2-mock-remote", "mock-runaway": "t2-mock-runaway"}

LOCAL_PRICE = {"input_cost_per_token": 0.000001, "output_cost_per_token": 0.000002}


def _model(name, backend, api_base, key_env, price, max_tokens=256):
    return {"model_name": name,
            "litellm_params": {"model": f"openai/{backend}", "api_base": api_base,
                               "api_key": f"os.environ/{key_env}", **price, "max_tokens": max_tokens},
            "model_info": {"max_output_tokens": 1024, "max_input_tokens": 8192}}


def build_configs() -> tuple[dict, dict]:
    base = yaml.safe_load((ROOT / "deploy" / "litellm" / "config.yaml").read_text())
    g = copy.deepcopy(base)
    g["model_list"] += [
        _model("mock-runaway", "mock-runaway", "http://mock-runaway:8000/v1", "MOCK_LOCAL_API_KEY", LOCAL_PRICE),
        _model("mock-local-broken", "mock-local", "http://mock-local:8999/v1", "MOCK_LOCAL_API_KEY", LOCAL_PRICE),
        _model("mock-local-dead", "mock-local", "http://mock-local:8999/v1", "MOCK_LOCAL_API_KEY", LOCAL_PRICE),
        _model("mock-flaky", "mock-local", "http://mock-local:8999/v1", "MOCK_LOCAL_API_KEY", LOCAL_PRICE),
        _model("mock-flaky", "mock-local", "http://mock-local:8000/v1", "MOCK_LOCAL_API_KEY", LOCAL_PRICE),
    ]
    g.setdefault("router_settings", {})["fallbacks"] = [{"mock-local-broken": ["mock-remote"]}]
    # keep the dead mock-flaky deployment in rotation so every run really exercises retries
    g["router_settings"]["disable_cooldowns"] = True
    g["general_settings"]["proxy_batch_write_at"] = LAG_SECONDS
    assert "callbacks.budget_guard.budget_guard" in (g.get("litellm_settings", {}).get("callbacks") or []), \
        "deploy/litellm/config.yaml must wire the budget guard"
    n = copy.deepcopy(g)
    n["litellm_settings"].pop("callbacks", None)
    return g, n


def write_configs() -> None:
    OUT.mkdir(parents=True, exist_ok=True)
    g, n = build_configs()
    hdr = "# GENERATED by tests/budget/stack/t2stack.py from deploy/litellm/config.yaml. Do not edit.\n"
    (OUT / "config.guarded.yaml").write_text(hdr + yaml.safe_dump(g, sort_keys=False))
    (OUT / "config.native.yaml").write_text(hdr + yaml.safe_dump(n, sort_keys=False))


def compose(*args: str, check: bool = True, timeout: int = 600) -> subprocess.CompletedProcess:
    cmd = ["docker", "compose", "-p", PROJECT, "--env-file", str(ROOT / "deploy" / ".env")]
    for f in COMPOSE_FILES:
        cmd += ["-f", str(f)]
    env = {**os.environ, "GATEWAY_PORT": str(GUARDED_PORT), "T2_NATIVE_PORT": str(NATIVE_PORT)}
    return subprocess.run(cmd + list(args), capture_output=True, text=True, env=env, timeout=timeout, check=check)


def up() -> None:
    write_configs()
    r = compose("up", "-d", "--wait", "--wait-timeout", "300", check=False)
    if r.returncode != 0:
        raise RuntimeError(f"t2 stack up failed:\n{r.stdout}\n{r.stderr}")


def down() -> None:
    compose("down", "--volumes", "--remove-orphans", check=False)


def is_up() -> bool:
    r = compose("ps", "--format", "{{.Name}} {{.Health}}", check=False)
    lines = [l for l in r.stdout.splitlines() if l.strip()]
    return len(lines) >= len(CONTAINERS) and all(l.endswith("healthy") for l in lines)


if __name__ == "__main__":
    {"up": up, "down": down, "configs": write_configs}[sys.argv[1]]()
