#!/usr/bin/env python
"""Release artifacts (T9): release/images.lock + SBOMs in release/sbom/.

  python scripts/release_artifacts.py            write images.lock, generate SBOMs (syft), write sbom/INDEX.md
  python scripts/release_artifacts.py --lock     only images.lock (no Docker needed for the file itself)
  python scripts/release_artifacts.py --check    fail if a compose file / Dockerfile pin is missing from the lock

images.lock lists every third-party image the stack runs, pinned by digest, taken from the digests written into
deploy/*.yml, deploy/hardening/*.yml, tests/*/stack/*.yml and the Dockerfile base images. Images built from this repo
(govpilot/*) are listed as comments with their local image id: they are rebuilt from source, not pulled.

SBOMs: Syft (official image anchore/syft, pinned below) scans each image through the Docker socket and writes
CycloneDX JSON. Where Docker or Syft is unavailable the fallback emits a package-level SBOM from `pip freeze`
inside the image (Python packages only, flagged as such in its metadata).
"""
from __future__ import annotations

import json
import pathlib
import re
import subprocess
import sys

ROOT = pathlib.Path(__file__).resolve().parents[1]
SYFT = "anchore/syft@sha256:500e2d872ac019436926e8322b4fc1f39441d94d21f6f4046c6ff29b30e8cb02"
LOCK = ROOT / "release" / "images.lock"
SBOM_DIR = ROOT / "release" / "sbom"


def sh(*a, check=True, timeout=600):
    return subprocess.run(list(a), capture_output=True, text=True, encoding="utf-8", errors="replace", timeout=timeout, check=check,
                          env={**__import__("os").environ, "MSYS_NO_PATHCONV": "1"})


def pinned_images() -> dict[str, str]:
    """ref (without digest) -> digest, from every compose file and Dockerfile in the repo."""
    out: dict[str, str] = {}
    files = (list((ROOT / "deploy").glob("*.yml")) + list((ROOT / "deploy" / "hardening").glob("*.yml"))
             + list((ROOT / "tests").glob("*/stack/*.yml")))
    for f in files:
        for m in re.finditer(r"^\s*image:\s*(\S+?)@(sha256:[0-9a-f]{64})", f.read_text(encoding="utf-8"), re.M):
            out[m.group(1)] = m.group(2)
    for f in list((ROOT / "services").glob("*/Dockerfile")) + [ROOT / "agents" / "Dockerfile"]:
        for m in re.finditer(r"^FROM\s+(\S+?)@(sha256:[0-9a-f]{64})", f.read_text(encoding="utf-8"), re.M):
            out[m.group(1)] = m.group(2)
    return out


def unpinned() -> list[str]:
    bad = []
    for f in (list((ROOT / "deploy").glob("*.yml")) + list((ROOT / "deploy" / "hardening").glob("*.yml"))):
        for m in re.finditer(r"^\s*image:\s*(\S+)", f.read_text(encoding="utf-8"), re.M):
            if not m.group(1).startswith("govpilot/") and "@sha256:" not in m.group(1):
                bad.append(f"{f.name}: {m.group(1)}")
    for f in list((ROOT / "services").glob("*/Dockerfile")) + [ROOT / "agents" / "Dockerfile"]:
        for m in re.finditer(r"^FROM\s+(\S+)", f.read_text(encoding="utf-8"), re.M):
            if "@sha256:" not in m.group(1):
                bad.append(f"{f.relative_to(ROOT)}: FROM {m.group(1)}")
    return bad


def local_images() -> dict[str, str]:
    out = {}
    for ref in ("govpilot/agents:1", "govpilot/control-plane:1", "govpilot/discovery:1", "govpilot/mock-provider:1",
                "govpilot/status-page:1"):
        r = sh("docker", "image", "inspect", ref, "--format", "{{.Id}}", check=False)
        if r.returncode == 0:
            out[ref] = r.stdout.strip()
    return out


def write_lock(pins: dict[str, str], local: dict[str, str]) -> None:
    LOCK.parent.mkdir(parents=True, exist_ok=True)
    lines = ["# release/images.lock: every third-party image the pilot runs, pinned by digest.",
             "# Format: <image ref without digest> <digest>. Generated by scripts/release_artifacts.py from the digests",
             "# in deploy/*.yml, deploy/hardening/*.yml, tests/*/stack/*.yml and the Dockerfile base images;",
             "# tests/hardening checks the compose files, the Dockerfiles and the running containers against it.",
             "# To upgrade an image: pull it, replace the digest in the compose file / Dockerfile, rerun this script,",
             "# rerun tests/hardening and the acceptance suite (docs/runbook/ has the patch procedure).", ""]
    for ref in sorted(pins):
        lines.append(f"{ref} {pins[ref]}")
    lines += ["", "# Built from this repository (not pulled); the id changes with every rebuild. Base image is pinned above."]
    for ref in sorted(local):
        lines.append(f"# built {ref} {local[ref]}")
    lines += ["", f"# tooling (not part of the running stack): {SYFT}"]
    LOCK.write_text("\n".join(lines) + "\n", encoding="utf-8", newline="\n")
    print(f"wrote {LOCK.relative_to(ROOT)} ({len(pins)} pinned images)")


def slug(ref: str) -> str:
    return re.sub(r"[^A-Za-z0-9._-]+", "_", ref)


def syft_sbom(ref: str, out: pathlib.Path) -> dict | None:
    r = sh("docker", "run", "--rm", "-v", "/var/run/docker.sock:/var/run/docker.sock", SYFT, f"docker:{ref}",
           "-o", "cyclonedx-json=/dev/stdout", "-q", check=False, timeout=900)
    if r.returncode != 0 or not r.stdout.startswith("{"):
        print(f"  syft failed for {ref}: {r.stderr[-300:]}")
        return None
    bom = json.loads(r.stdout)
    bom.get("metadata", {}).pop("timestamp", None)              # reproducible: no run time in the committed file
    bom.pop("serialNumber", None)
    out.write_text(json.dumps(bom, indent=1, sort_keys=True) + "\n", encoding="utf-8", newline="\n")
    return bom


def pip_fallback(ref: str, out: pathlib.Path) -> dict | None:
    r = sh("docker", "run", "--rm", "--entrypoint", "sh", ref, "-c",
           "python -m pip freeze 2>/dev/null || /app/.venv/bin/python -m pip freeze 2>/dev/null", check=False)
    pkgs = [ln.split("==") for ln in r.stdout.splitlines() if "==" in ln]
    if not pkgs:
        return None
    bom = {"bomFormat": "CycloneDX", "specVersion": "1.5", "version": 1,
           "metadata": {"component": {"type": "container", "name": ref},
                        "properties": [{"name": "govpilot:scope", "value": "python packages only (pip freeze fallback)"}]},
           "components": [{"type": "library", "name": n, "version": v, "purl": f"pkg:pypi/{n.lower()}@{v}"} for n, v in pkgs]}
    out.write_text(json.dumps(bom, indent=1, sort_keys=True) + "\n", encoding="utf-8", newline="\n")
    return bom


def licenses(bom: dict) -> dict[str, int]:
    out: dict[str, int] = {}
    for c in bom.get("components", []):
        ls = c.get("licenses") or []
        names = [(x.get("license") or {}).get("id") or (x.get("license") or {}).get("name") or x.get("expression")
                 for x in ls] or ["(none declared)"]
        for n in names:
            out[str(n)] = out.get(str(n), 0) + 1
    return out


def main(argv: list[str]) -> int:
    pins = pinned_images()
    if "--check" in argv:
        bad = unpinned()
        lock = LOCK.read_text(encoding="utf-8") if LOCK.exists() else ""
        for ref, d in pins.items():
            if f"{ref} {d}" not in lock:
                bad.append(f"lock is stale for {ref}")
        print("\n".join(bad) or "ok")
        return 1 if bad else 0
    local = local_images()
    write_lock(pins, local)
    if "--lock" in argv:
        return 0
    SBOM_DIR.mkdir(parents=True, exist_ok=True)
    rows = []
    targets = [f"{ref}@{d}" for ref, d in sorted(pins.items())] + sorted(local)
    for ref in targets:
        name = slug(ref.split("@")[0])
        out = SBOM_DIR / f"{name}.cdx.json"
        print(f"sbom {ref}")
        bom = syft_sbom(ref, out) or pip_fallback(ref, out)
        if bom is None:
            rows.append((ref, "FAILED", "", ""))
            continue
        lic = licenses(bom)
        top = ", ".join(f"{k} ({v})" for k, v in sorted(lic.items(), key=lambda kv: -kv[1])[:6])
        rows.append((ref, out.name, str(len(bom.get("components", []))), top))
    idx = ["# SBOM index", "",
           "CycloneDX JSON generated by Syft (`" + SYFT + "`) through `scripts/release_artifacts.py`. One file per image.",
           "Regenerate after any image change; commit together with `release/images.lock`.", "",
           "| Image | SBOM file | Components | Most common declared licenses |", "|---|---|---|---|"]
    for ref, f, n, top in rows:
        idx.append(f"| `{ref.split('@')[0]}` | `{f}` | {n} | {top} |")
    (SBOM_DIR / "INDEX.md").write_text("\n".join(idx) + "\n", encoding="utf-8", newline="\n")
    print(f"wrote {SBOM_DIR.relative_to(ROOT)}/INDEX.md")
    return 0 if all(r[1] != "FAILED" for r in rows) else 1


if __name__ == "__main__":
    sys.exit(main(sys.argv[1:]))
