"""Derive the OTel-enabled gateway config for the `gateway-demo` profile.

Reads deploy/litellm/config.yaml (never edits it), appends the `otel` callback, writes
.local/observability/litellm-otel.yaml. The equivalent change for the real gateway is the one line
documented in docs/results/T6.md (`litellm_settings.callbacks: [..., "otel"]` + three env vars).
"""
from pathlib import Path

import yaml

ROOT = Path(__file__).resolve().parents[2]
cfg = yaml.safe_load((ROOT / "deploy/litellm/config.yaml").read_text(encoding="utf-8"))
ls = cfg.setdefault("litellm_settings", {})
cbs = list(ls.get("callbacks") or [])
if "otel" not in cbs:
    cbs.append("otel")
ls["callbacks"] = cbs
out = ROOT / ".local/observability/litellm-otel.yaml"
out.parent.mkdir(parents=True, exist_ok=True)
out.write_text("# GENERATED by deploy/observability/make-gateway-config.py - do not edit\n"
               + yaml.safe_dump(cfg, sort_keys=False), encoding="utf-8")
print("wrote", out)
